import type { AtlasCanonicalIntent } from './atlasKnowledge';

export const ATLAS_KNOWLEDGE_VERSION = '2026-08-22.1';

export type AtlasReviewedPhrase = {
  phrase: string;
  canonicalIntent: AtlasCanonicalIntent;
  category: 'formal' | 'informal' | 'short' | 'manager' | 'industry' | 'grammar';
};

const groups: Record<AtlasCanonicalIntent, readonly string[]> = {
  morning_briefing: ['show the morning briefing', 'give me the morning brief', 'brief me on fleet operations', 'what needs attention this morning', 'what should I know before the shift', 'give me the operations attention queue', 'what are the current fleet exceptions', 'start with the important operational items', 'what is on the morning attention list', 'summarise the operational briefing'],
  yesterday_carry_over: ['show yesterday carry over', 'what remains from yesterday', 'what is outstanding from yesterday', 'list unresolved items from yesterday', 'anything still open from yesterday', 'which issues carried over overnight', 'what did not get resolved yesterday', 'show yesterday unresolved work', 'what needs following up from yesterday', 'what came forward from the previous day'],
  today_attention: ['show todays operational work', 'what is happening today', 'what work is planned today', 'list todays exceptions', 'what needs attention today', 'show the current days issues', 'anything happening on todays rota', 'what is active today', 'which jobs need attention today', 'what should the team handle today'],
  tomorrow_conflicts: ['show tomorrows conflicts', 'what is planned for tomorrow', 'what conflicts are there tomorrow', 'list tomorrows assignment issues', 'which drivers have problems tomorrow', 'what needs checking before tomorrow', 'show tomorrow acknowledgement issues', 'anything due to clash tomorrow', 'what is at risk on tomorrows rota', 'which compliance warnings affect tomorrow'],
  next30_warnings: ['show warnings in the next 30 days', 'what expires in the next month', 'list the next 30 day warnings', 'which evidence expires soon', 'show upcoming compliance warnings', 'what is due within 30 days', 'which documents need action this month', 'show the next month compliance horizon', 'what warnings are newly due soon', 'what needs renewing in the next few weeks'],
  asset_readiness_reason: ['why is this vehicle blocked', 'why is this unit prohibited', 'why cannot I allocate this asset', 'explain the readiness result', 'what is wrong with this vehicle', 'show the readiness reason', 'why is the trailer not ready', 'what caused the assignment block', 'why did readiness fail', 'explain why this asset cannot work'],
  assets_prohibited: ['show vehicles currently marked VOR', 'which vehicles are VOR', 'list the VOR units', 'any trucks off the road', 'which assets are prohibited', 'what can I not allocate today', 'show units unavailable for assignment', 'list vehicles not fit for assignment', 'which fleet assets are grounded', 'show the hard blocked vehicles'],
  assets_ready: ['show assets ready for assignment', 'which vehicles are ready', 'list ready fleet units', 'what can be allocated now', 'show vehicles with ready status', 'which assets passed readiness', 'list assignable vehicles', 'show trailers ready to work', 'which units have no readiness block', 'show the ready asset list'],
  asset_defects: ['show unresolved vehicle defects', 'which vehicles have safety defects', 'list open fleet faults', 'are there any open safety issues', 'show outstanding vehicle issues', 'which defects are not fixed', 'list unresolved workshop defects', 'what safety faults remain open', 'show vehicles with an open defect', 'which fleet issues need repair'],
  jobs_acknowledgement: ['show jobs awaiting acknowledgement', 'which assignments are not acknowledged', 'list unacknowledged jobs', 'has the driver acknowledged the work', 'show published jobs waiting for acceptance', 'which jobs still need driver acknowledgement', 'list assignments awaiting a drivers response', 'what work has not been acknowledged', 'show acknowledgement exceptions', 'which published work is still waiting'],
  jobs_exceptions: ['show delayed jobs', 'which jobs have an exception', 'list jobs with vehicle issues', 'show unable to complete jobs', 'which deliveries are delayed', 'what job execution problems are open', 'show site and route issues', 'list driver recorded job exceptions', 'which work needs exception follow up', 'show active job incidents'],
  jobs_for_driver: ['what has Dave got tomorrow', 'show Sarahs assigned work', 'which jobs are assigned to this driver', 'list this drivers jobs', 'what work does the driver have', 'show the drivers current assignments', 'which runs belong to Dave', 'what is on the drivers shift', 'show jobs for the selected driver', 'list assignments for this person'],
  jobs_for_date: ['show jobs for tomorrow', 'list work on todays rota', 'which jobs are planned for Friday', 'show assignments for this date', 'what deliveries are scheduled today', 'list the jobs on tomorrows shift', 'which work is planned for the selected day', 'show the days assignments', 'what runs are due on this date', 'list jobs by rota date'],
  driver_compliance: ['show driver compliance warnings', 'which drivers have compliance issues', 'list licence CPC and medical warnings', 'show driver evidence needing review', 'which driver documents are expiring', 'give me the driver compliance forecast', 'show current driver qualification risks', 'which drivers need document action', 'list driver evidence problems', 'show the driver compliance horizon'],
  driver_upcoming_expiry: ['which driver documents expire soon', 'show driver evidence due within 30 days', 'list upcoming driver expiries', 'who has a licence expiring soon', 'show CPC expiry warnings', 'which medical records are nearly due', 'list driver renewals needed this month', 'what driver evidence is due next', 'show the driver expiry list', 'which personnel dates need attention'],
  driver_assignment_conflict: ['which drivers have future assignment conflicts', 'show planned compliance conflicts', 'list drivers with assignment date risks', 'which future jobs need driver evidence review', 'show driver conflicts after expiry', 'what driver plans need checking', 'list assignments beyond evidence dates', 'which drivers may need a rota review', 'show future driver planning warnings', 'what compliance conflicts affect assignments'],
  asset_compliance: ['show vehicle compliance warnings', 'which vehicle evidence is expiring', 'list asset compliance issues', 'show MOT and PMI warnings', 'which vehicles need compliance action', 'what fleet evidence is due soon', 'show annual test and maintenance warnings', 'list vehicle documents needing review', 'which assets have compliance dates', 'show the asset compliance forecast'],
  task_queue: ['show the operational task queue', 'list open operational tasks', 'what tasks are open', 'show my fleet task list', 'which tasks need action', 'list active operations tasks', 'show the manager task queue', 'what remains in the task queue', 'display outstanding operational actions', 'show unresolved operational tasks'],
  unresolved_tasks: ['show unresolved tasks', 'which tasks remain open', 'list tasks not resolved', 'what operational tasks are outstanding', 'show active unresolved actions', 'which source issues still have tasks', 'list tasks awaiting resolution', 'what work is still unresolved', 'show re-opened tasks', 'which tasks need a source change'],
  pod_review: ['show POD evidence awaiting review', 'which proof of delivery records need review', 'list delivery evidence for manager review', 'show POD follow up items', 'what delivery proof is pending', 'which job evidence needs a decision', 'list POD records needing attention', 'show evidence attached to jobs for review', 'which delivery notes await review', 'show pending job evidence'],
  pod_follow_up: ['show POD evidence needing follow up', 'which delivery records need more evidence', 'list manager POD follow ups', 'what POD review cases are incomplete', 'show delivery evidence requests', 'which job evidence needs a response', 'list POD cases returned for follow up', 'what evidence should the driver add', 'show unresolved POD review items', 'which delivery proof needs clarification'],
  pod_status: ['what is the POD status', 'show the delivery evidence status', 'has this job got POD', 'is the proof of delivery pending', 'check this jobs evidence state', 'what happened to the POD review', 'show evidence review status', 'is delivery proof complete', 'which outcome was recorded for POD', 'give me the job evidence status'],
  jobs_incomplete: ['show incomplete jobs', 'which jobs could not be completed', 'list work that is still incomplete', 'show unable to complete records', 'which deliveries need completion follow up', 'what jobs remain unfinished', 'list incomplete assignments', 'show jobs with no completion outcome', 'which runs were not completed', 'show unfinished operational work'],
  driver_missing_evidence: ['which drivers are missing documents', 'show drivers without required evidence', 'list missing driver licence evidence', 'which drivers have no medical evidence', 'show missing CPC evidence for drivers', 'who needs a document upload', 'which driver records are incomplete', 'list drivers with evidence gaps', 'show drivers with missing compliance proof', 'which personnel documents are absent'],
  trailer_compliance: ['show trailer compliance warnings', 'which trailers have due dates', 'list trailer annual test issues', 'show trailer readiness evidence', 'which trailers need compliance action', 'what trailer documents expire soon', 'list trailer defects affecting readiness', 'show trailers not ready for assignment', 'which trailer checks are outstanding', 'show the trailer compliance forecast'],
  task_reason: ['why is this task open', 'explain the task source', 'what caused this operational task', 'why did this task reappear', 'show the evidence behind this task', 'what source issue created the task', 'why is the task still unresolved', 'explain the current task status', 'what authoritative record supports this task', 'why did resolving handling not close the task'],
  operational_health: ['show operational health', 'how is the fleet doing', 'give me the current operations health', 'are there any serious fleet issues', 'show the overall attention picture', 'what is the health of todays operation', 'summarise fleet exceptions', 'are operations in a safe state', 'show current operational risks', 'what is the current fleet position'],
  job_status: ['what is the status of this job', 'has this job been acknowledged', 'show assignment status', 'is the job still published', 'what state is this assignment in', 'check this jobs current status', 'show the lifecycle status', 'is this work delayed', 'what happened to this assignment', 'give me the job status'],
  proposal_status: ['show pending Atlas proposals', 'which proposals are stale', 'list Atlas proposals awaiting review', 'what proposals were applied', 'show the proposal status', 'which operational proposals need review', 'are any Atlas proposals stale', 'list proposal outcomes', 'show unapplied proposals', 'what is the current proposal queue'],
  faq_vor: ['what does VOR mean', 'what is VOR', 'define vehicle off road', 'explain off road status', 'what does off road mean in HourWise', 'what is a prohibited vehicle', 'what does grounded mean for a vehicle', 'why can VOR prevent allocation', 'what is the VOR rule', 'tell me about VOR'],
  faq_pod: ['what does POD mean', 'what is proof of delivery', 'explain delivery evidence', 'what is a delivery note in HourWise', 'does uploading POD complete a job', 'who reviews POD evidence', 'what is delivery proof', 'how does job evidence work', 'what happens to failed delivery evidence', 'explain the POD review workflow'],
  faq_compliance: ['what is CPC', 'what is DQC', 'what is PMI', 'what is medical evidence', 'what does missing evidence mean', 'what does action required mean', 'what is a compliance warning', 'what is future compliance conflict', 'is a forecast a legal decision', 'explain unknown compliance evidence'],
  faq_atlas: ['what can Atlas answer', 'does Atlas use AI', 'is Atlas inference enabled', 'what does deterministic Atlas mean', 'can Atlas change a job', 'can Atlas make a planning decision', 'what happens when Atlas cannot answer', 'does Atlas call an external model', 'what is Atlas allowed to change', 'explain Atlas inference status'],
  unknown: [],
};

const categories: AtlasReviewedPhrase['category'][] = ['formal', 'informal', 'short', 'manager', 'industry', 'grammar'];
export const ATLAS_REVIEWED_PHRASES: AtlasReviewedPhrase[] = Object.entries(groups).flatMap(([canonicalIntent, phrases]) => phrases.map((phrase, index) => ({ phrase, canonicalIntent: canonicalIntent as AtlasCanonicalIntent, category: categories[index % categories.length] })));

export type AtlasNegativeExample = { phrase: string; expected: 'clarification' | 'faq' | 'reasoning_required' | 'unknown'; mustNotMatch: AtlasCanonicalIntent };
export const ATLAS_NEGATIVE_EXAMPLES: AtlasNegativeExample[] = [
  { phrase: 'which vehicles are not VOR', expected: 'clarification', mustNotMatch: 'assets_prohibited' },
  { phrase: 'what does VOR mean', expected: 'faq', mustNotMatch: 'assets_prohibited' },
  { phrase: 'why was this vehicle previously VOR', expected: 'clarification', mustNotMatch: 'assets_prohibited' },
  { phrase: 'can I remove a VOR status', expected: 'clarification', mustNotMatch: 'assets_prohibited' },
  { phrase: 'drivers without missing documents', expected: 'clarification', mustNotMatch: 'driver_missing_evidence' },
  { phrase: "jobs that aren't delayed", expected: 'clarification', mustNotMatch: 'jobs_exceptions' },
  { phrase: 'what is happening', expected: 'clarification', mustNotMatch: 'morning_briefing' },
  { phrase: 'tell me a joke', expected: 'unknown', mustNotMatch: 'morning_briefing' },
  { phrase: 'write a customer email about the late delivery', expected: 'reasoning_required', mustNotMatch: 'jobs_exceptions' },
  { phrase: 'replan tomorrow after Dave calls in sick', expected: 'reasoning_required', mustNotMatch: 'tomorrow_conflicts' },
  { phrase: 'which driver is best for this job', expected: 'reasoning_required', mustNotMatch: 'driver_compliance' },
  { phrase: 'optimise the fleet for next week', expected: 'reasoning_required', mustNotMatch: 'next30_warnings' },
  { phrase: 'what was the vehicle status last year', expected: 'clarification', mustNotMatch: 'assets_prohibited' },
  { phrase: 'is trailer T123 legally compliant', expected: 'clarification', mustNotMatch: 'trailer_compliance' },
  { phrase: 'show me all jobs and all vehicles and all drivers and all trailers', expected: 'clarification', mustNotMatch: 'jobs_exceptions' },
  { phrase: 'what does the weather look like', expected: 'unknown', mustNotMatch: 'operational_health' },
  { phrase: 'which vehicle registration should I buy', expected: 'reasoning_required', mustNotMatch: 'assets_prohibited' },
  { phrase: 'remove this task from the database', expected: 'clarification', mustNotMatch: 'task_queue' },
  { phrase: 'tell me the drivers personal phone numbers', expected: 'unknown', mustNotMatch: 'driver_compliance' },
  { phrase: 'what is the cheapest route', expected: 'reasoning_required', mustNotMatch: 'operational_health' },
];

export type AtlasFaqEntry = { id: string; phrase: string; canonicalIntent: Extract<AtlasCanonicalIntent, 'faq_vor' | 'faq_pod' | 'faq_compliance' | 'faq_atlas'>; answer: string; navigationTarget: string };
export const ATLAS_FAQ_ENTRIES: AtlasFaqEntry[] = [
  { id: 'vor-definition', phrase: 'what does VOR mean', canonicalIntent: 'faq_vor', answer: 'VOR means vehicle off road. HourWise treats VOR or an unresolved safety defect as a deterministic assignment prohibition until the authoritative readiness state changes.', navigationTarget: '/dashboard?workspace=fleet&fleet=vehicles' },
  { id: 'vor-prohibited', phrase: 'what is a prohibited vehicle', canonicalIntent: 'faq_vor', answer: 'A prohibited vehicle has a hard readiness block such as VOR or an unresolved safety defect. The readiness record is authoritative for allocation.', navigationTarget: '/dashboard?workspace=fleet&fleet=vehicles' },
  { id: 'pod-definition', phrase: 'what does POD mean', canonicalIntent: 'faq_pod', answer: 'POD is proof of delivery evidence attached to a real job assignment. Manager review remains authoritative and uploading evidence does not complete the job.', navigationTarget: '/dashboard?workspace=people&people=jobs&panel=pod-review' },
  { id: 'pod-failed-delivery', phrase: 'what happens to failed delivery evidence', canonicalIntent: 'faq_pod', answer: 'Failed-delivery or unable-to-complete evidence remains attached to the job for governed manager review. It does not itself transition the job to complete.', navigationTarget: '/dashboard?workspace=people&people=jobs&panel=pod-review' },
  { id: 'pmi-definition', phrase: 'what is PMI', canonicalIntent: 'faq_compliance', answer: 'PMI is a planned maintenance inspection record in the Portal asset-compliance view. The Portal surfaces the recorded date and evidence state as operational guidance.', navigationTarget: '/dashboard?workspace=fleet&fleet=vehicles' },
  { id: 'cpc-definition', phrase: 'what is CPC', canonicalIntent: 'faq_compliance', answer: 'CPC/DQC is driver qualification evidence held in the current personnel record. HourWise forecasts the recorded expiry or missing evidence without making a legal determination.', navigationTarget: '/dashboard?workspace=people&people=drivers' },
  { id: 'dqc-definition', phrase: 'what is DQC', canonicalIntent: 'faq_compliance', answer: 'DQC is the driver qualification card evidence represented by the Portal CPC/DQC record. Review the authoritative personnel document and expiry date.', navigationTarget: '/dashboard?workspace=people&people=drivers' },
  { id: 'unknown-evidence', phrase: 'what does unknown compliance evidence mean', canonicalIntent: 'faq_compliance', answer: 'Unknown means the Portal cannot establish a usable authoritative date or evidence state. It is kept distinct from confirmed missing evidence.', navigationTarget: '/dashboard?workspace=people&people=drivers' },
  { id: 'future-conflict', phrase: 'what is future compliance conflict', canonicalIntent: 'faq_compliance', answer: 'A future compliance conflict means a planned assignment falls after an evidence expiry or lacks required evidence. It is a planning warning, not a claim of future illegality.', navigationTarget: '/dashboard?workspace=people&people=drivers' },
  { id: 'atlas-deterministic', phrase: 'what does deterministic Atlas mean', canonicalIntent: 'faq_atlas', answer: 'Deterministic Atlas answers from company-scoped Portal state and events using reviewed rules. No model or external inference provider is called.', navigationTarget: '/dashboard?workspace=people&people=atlas' },
  { id: 'atlas-disabled', phrase: 'is Atlas inference enabled', canonicalIntent: 'faq_atlas', answer: 'Paid Atlas inference is not configured in this release. Deterministic Atlas remains active and available.', navigationTarget: '/dashboard?workspace=people&people=atlas' },
  { id: 'atlas-change', phrase: 'can Atlas change a job', canonicalIntent: 'faq_atlas', answer: 'Atlas cannot directly change authoritative job state from a deterministic question. Governed proposal and lifecycle paths remain authoritative for any change.', navigationTarget: '/dashboard?workspace=people&people=jobs' },
  { id: 'task-reopen', phrase: 'why did this task reappear', canonicalIntent: 'faq_atlas', answer: 'A task can reopen when its authoritative source issue is still active or its source fingerprint changes. Handling state cannot suppress unresolved source evidence.', navigationTarget: '/dashboard?workspace=people&people=tasks' },
  { id: 'stale-proposal', phrase: 'what does stale mean for an Atlas proposal', canonicalIntent: 'faq_atlas', answer: 'A stale proposal was produced from facts that have changed or exceeded its validity boundary. Revalidation is required before any governed action.', navigationTarget: '/dashboard?workspace=people&people=atlas' },
  { id: 'stale-route', phrase: 'what does a stale route estimate mean', canonicalIntent: 'faq_atlas', answer: 'A stale route estimate is no longer within its recorded freshness boundary. The Portal does not treat it as live distance or ETA evidence.', navigationTarget: '/dashboard?workspace=people&people=jobs' },
];

export const ATLAS_PHRASE_COUNT = ATLAS_REVIEWED_PHRASES.length;
export const ATLAS_NEGATIVE_EXAMPLE_COUNT = ATLAS_NEGATIVE_EXAMPLES.length;
