import { useEffect, useState } from 'react';
import { Lock, Save } from 'lucide-react';
import { fetchGovernedAtlasPolicy, updateGovernedAtlasPolicy, type GovernedAtlasPolicy } from '../../lib/atlasPolicyAdministration';

export function AtlasPolicyAdministration() {
  const [policy, setPolicy] = useState<GovernedAtlasPolicy | null>(null);
  const [enabled, setEnabled] = useState(false);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  useEffect(() => { let cancelled = false; void fetchGovernedAtlasPolicy().then((result) => { if (!cancelled) { setPolicy(result); setEnabled(result?.enabled ?? false); } }).catch((error: unknown) => { if (!cancelled) setMessage(error instanceof Error ? error.message : 'Policy administration is not available to this manager.'); }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, []);
  const save = async () => { setSaving(true); setMessage(null); try { const result = await updateGovernedAtlasPolicy({ enabled, allowedTiers: policy?.allowedTiers ?? ['SYNTHESIS', 'STANDARD', 'DEEP'], monthlyBudgetMinorUnits: policy?.monthlyBudgetMinorUnits ?? null, perRequestBudgetMinorUnits: policy?.perRequestBudgetMinorUnits ?? null, dailyRequestLimit: policy?.dailyRequestLimit ?? null, monthlyRequestLimit: policy?.monthlyRequestLimit ?? null }); setPolicy(result); setMessage('Governed policy saved. Deterministic Atlas remains available even when inference is disabled.'); } catch (error: unknown) { setMessage(error instanceof Error ? error.message : 'Unable to save the governed Atlas policy.'); } finally { setSaving(false); } };
  if (loading) return <div className="mt-5 rounded-xl border border-white/10 bg-white/5 p-4 text-xs text-hw-slate-400">Loading governed Atlas policy…</div>;
  if (!policy) return <div className="mt-5 rounded-xl border border-white/10 bg-white/5 p-4"><div className="flex items-center gap-2 text-xs font-bold text-hw-slate-300"><Lock className="h-4 w-4 text-hw-cyan-500" /> Atlas inference policy administration is restricted to the governed administrator permission.</div>{message ? <p className="mt-2 text-xs text-hw-slate-400">{message}</p> : null}</div>;
  return <div className="mt-5 rounded-xl border border-amber-500/20 bg-amber-500/5 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-widest text-amber-300">Governed Atlas policy</p><p className="mt-1 text-xs text-hw-slate-300">Owner/admin permission is required. This controls a future provider boundary; it does not enable a provider today.</p></div><Lock className="h-4 w-4 text-amber-300" /></div><label className="mt-4 flex items-center gap-3 text-xs font-bold text-hw-slate-200"><input type="checkbox" checked={enabled} onChange={(event) => setEnabled(event.target.checked)} /> Allow future approved inference tiers</label><p className="mt-2 text-[10px] text-hw-slate-500">Current approved tiers: {policy.allowedTiers.join(', ')}. Provider slot: {policy.providerSlot ?? 'not configured'}.</p><button type="button" onClick={() => void save()} disabled={saving} className="mt-4 inline-flex items-center gap-2 rounded-lg bg-amber-300 px-3 py-2 text-[10px] font-black uppercase tracking-widest text-hw-navy-950 disabled:opacity-50"><Save className="h-3.5 w-3.5" />{saving ? 'Saving…' : 'Save policy'}</button>{message ? <p className="mt-3 text-xs text-hw-slate-300">{message}</p> : null}</div>;
}
