// src/components/manager/DataRequestForm.tsx

import React, { useState } from 'react';
import { Shield, AlertCircle } from 'lucide-react';
import { useTranslation } from 'react-i18next';

export function DataRequestForm() {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [requestType, setRequestType] = useState<'download' | 'deletion'>('download');
  const [details, setDetails] = useState('');
  const [submitted, setSubmitted] = useState(false);
  const { t } = useTranslation();

  const privacyEmail = import.meta.env.VITE_PRIVACY_EMAIL_ADDRESS || 'privacy@hourwiseeu.co.uk';

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    const subject = `GDPR Data Request (${requestType === 'download' ? 'Access' : 'Erasure'}) - ${name}`;
    const body = `
      OFFICIAL DATA REQUEST
      ---------------------
      Name: ${name}
      Email: ${email}
      Request Type: ${requestType === 'download' ? 'Right of Access (Download)' : 'Right to Erasure (Deletion)'}

      Details:
      ${details || 'No additional details provided.'}

      ---
      This is an automated request generated by the HourWise EU Portal.
      The user will now send this from their verified email address.
    `;

    window.location.href = `mailto:${privacyEmail}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    setSubmitted(true);
  };

  if (submitted) {
    return (
      <div className="bg-blue-50 border border-blue-200 p-8 rounded-2xl text-center shadow-sm">
        <Shield className="w-12 h-12 text-blue-600 mx-auto mb-4" />
        <h2 className="text-xl font-bold text-slate-900 mb-2">{t('privacyRequest.form.success.title')}</h2>
        <p className="text-slate-600 mb-6">{t('privacyRequest.form.success.message')}</p>
        <button onClick={() => setSubmitted(false)} className="text-blue-600 font-bold hover:underline">{t('privacyRequest.form.success.submitAnother')}</button>
      </div>
    );
  }

  return (
    <div className="space-y-6 bg-white p-8 rounded-2xl shadow-xl border border-slate-100">
      <div className="bg-amber-50 border border-amber-200 p-4 rounded-xl flex items-start gap-3">
        <AlertCircle className="text-amber-600 shrink-0 mt-0.5" size={18} />
        <div className="text-xs text-amber-800 leading-relaxed">
          {t('privacyRequest.form.notices.fleet')}
        </div>
      </div>

      <form onSubmit={handleSubmit} className="space-y-5">
        <div>
          <label className="block text-[10px] font-black text-slate-400 uppercase mb-1.5 tracking-wider">{t('privacyRequest.form.labels.fullName')}</label>
          <input
            type="text"
            value={name}
            onChange={(e) => setName(e.target.value)}
            required
            placeholder={t('privacyRequest.form.placeholders.fullName')}
            className="w-full p-3 border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none text-slate-900 bg-white font-medium"
          />
        </div>

        <div>
          <label className="block text-[10px] font-black text-slate-400 uppercase mb-1.5 tracking-wider">{t('privacyRequest.form.labels.email')}</label>
          <input
            type="email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            required
            placeholder={t('privacyRequest.form.placeholders.email')}
            className="w-full p-3 border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none text-slate-900 bg-white font-medium"
          />
        </div>

        <div>
          <label className="block text-[10px] font-black text-slate-400 uppercase mb-1.5 tracking-wider">{t('privacyRequest.form.labels.requestType')}</label>
          <select
            value={requestType}
            onChange={(e) => setRequestType(e.target.value as 'download' | 'deletion')}
            className="w-full p-3 border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none bg-white text-slate-900 font-bold"
          >
            <option value="download">{t('privacyRequest.form.requestTypes.download')}</option>
            <option value="deletion">{t('privacyRequest.form.requestTypes.deletion')}</option>
          </select>
        </div>

        <div>
          <label className="block text-[10px] font-black text-slate-400 uppercase mb-1.5 tracking-wider">{t('privacyRequest.form.labels.additionalInfo')}</label>
          <textarea
            rows={3}
            value={details}
            onChange={(e) => setDetails(e.target.value)}
            placeholder={t('privacyRequest.form.placeholders.details')}
            className="w-full p-3 border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none text-slate-900 bg-white font-medium resize-none"
          />
        </div>

        <button
          type="submit"
          className="w-full py-4 bg-slate-900 text-white rounded-xl font-black uppercase tracking-widest text-xs hover:bg-black transition-all shadow-lg shadow-slate-200"
        >
          {t('privacyRequest.form.cta')}
        </button>
      </form>

      <p className="text-[10px] text-slate-400 text-center leading-relaxed">
        {t('privacyRequest.form.notices.security')}
      </p>
    </div>
  );
}
