import { AtlasIntent } from './atlasTypes';

export const atlasKnowledge: AtlasIntent[] = [
  {
    id: 'what-is-hourwise',
    title: 'What is HourWise EU?',
    keywords: [
      'what is hourwise',
      'what is hourwise eu',
      'what do you do',
      'what is this',
      'hourwise eu',
      'overview',
      'about',
      'explain hourwise',
      'what are you building',
      'what does hourwise do',
      'what is the product',
      'what is the platform',
    ],
    answer:
      'HourWise EU is a connected driver hours app and fleet compliance portal for UK/EU transport. The app helps drivers track work, driving, breaks and POA, while the portal helps operators manage shifts, checks, expenses, incidents, tachograph data and compliance actions. The long-term goal is to give drivers and transport managers one clearer place to manage day-to-day fleet records and compliance workflows.',
    followUps: ['Driver app', 'Fleet portal', 'Tachograph analysis', 'Features included', 'Early access'],
    cta: { label: 'Join early access', action: 'earlyAccess' },
  },

  {
    id: 'features-included',
    title: 'What features will be included?',
    keywords: [
      'what features will be included',
      'features included',
      'included features',
      'what features',
      'feature list',
      'what will it include',
      'what does it include',
      'what can it do',
      'capabilities',
      'tools included',
      'modules',
      'what are the main features',
    ],
    answer:
      'HourWise is being built around two connected products: a driver app and a fleet portal. Planned and in-progress features include driver hours tracking, work time, driving time, breaks, POA, spoken alerts, daily reports, expenses, pay estimates, vehicle checks, defect reporting, incident records, fleet messaging, tachograph file analysis, driver card views, vehicle unit imports, compliance reminders, reports, document tracking and Atlas assistant summaries. Some features will launch earlier than others during beta.',
    followUps: ['Driver app features', 'Fleet portal features', 'Tachograph analysis', 'Atlas assistant', 'Early access'],
    cta: { label: 'Request early access', action: 'earlyAccess' },
  },

  {
    id: 'who-is-it-for',
    title: 'Who is HourWise for?',
    keywords: [
      'who is it for',
      'who is hourwise for',
      'target users',
      'users',
      'customers',
      'is this for drivers',
      'is this for fleets',
      'small fleets',
      'transport managers',
      'owner drivers',
      'hgv drivers',
      'operators',
      'fleet managers',
    ],
    answer:
      'HourWise is designed for professional drivers, solo drivers, small fleets, growing operators and transport managers who need clearer driver hours, fleet records and compliance visibility. The app can support individual drivers, while the portal is aimed at companies that need to manage drivers, vehicles, checks, reports and tachograph data in one place.',
    followUps: ['Solo driver', 'Fleet driver', 'Fleet portal', 'Pricing'],
  },

  {
    id: 'app-vs-portal',
    title: 'What is the difference between the app and the portal?',
    keywords: [
      'app vs portal',
      'difference between app and portal',
      'driver app and portal',
      'how do they work together',
      'connected app',
      'connected portal',
      'cab to office',
      'mobile and web',
      'driver to office',
    ],
    answer:
      'The driver app is for the person in the cab. It helps track work, driving, breaks, POA, expenses, checks and daily records. The fleet portal is for the office or transport manager. It brings together driver records, vehicle information, compliance actions, tachograph analysis, reports, defects, incidents and messages. The aim is for information captured by the driver to flow securely into the portal for review and action.',
    followUps: ['Driver app', 'Fleet portal', 'Vehicle checks', 'Reports'],
  },

  {
    id: 'driver-app',
    title: 'Driver app features',
    keywords: [
      'driver app',
      'mobile app',
      'what does the app do',
      'track hours',
      'work timer',
      'driving timer',
      'break timer',
      'poa',
      'alerts',
      'driver features',
      'app features',
      'shift timer',
      'driver hours app',
    ],
    answer:
      'The driver app is designed to help professional drivers track shifts, work time, driving time, breaks and POA, with alerts before key limits. It also supports daily reports, expenses, pay estimates, manual edits, calendar history, spoken reminders and fleet-connected workflows such as vehicle checks, defects, incident reporting and messages from the transport office.',
    followUps: ['Solo driver', 'Fleet driver', 'Alerts', 'Expenses', 'Pay estimates'],
  },

  {
    id: 'solo-driver',
    title: 'Can solo drivers use HourWise?',
    keywords: [
      'solo driver',
      'individual driver',
      'self employed',
      'self-employed',
      'owner driver',
      'agency driver',
      'can i use it alone',
      'without fleet',
      'single driver',
      'one driver',
    ],
    answer:
      'Yes. The driver app is planned to support solo drivers who want to track work, driving, breaks, POA, expenses, pay estimates and daily reports without needing a fleet portal account. This is useful for self-employed, agency or owner drivers who want clearer records and reminders during the working day.',
    followUps: ['Driver app features', 'Pricing', 'Reports', 'Early access'],
    cta: { label: 'Join early access', action: 'earlyAccess' },
  },

  {
    id: 'fleet-driver',
    title: 'How does it work for fleet drivers?',
    keywords: [
      'fleet driver',
      'company driver',
      'drivers connected to fleet',
      'driver connected to portal',
      'clock in',
      'clock out',
      'driver records',
      'fleet app',
      'employee driver',
    ],
    answer:
      'For fleet-connected drivers, the app can become a direct link between the driver and the transport office. Drivers may be able to submit shift records, vehicle checks, defects, incidents, expenses, receipts and acknowledgements. Managers can then review that information in the fleet portal and keep records organised.',
    followUps: ['Fleet portal', 'Vehicle checks', 'Messaging', 'Expenses'],
  },

  {
    id: 'fleet-portal',
    title: 'Fleet portal features',
    keywords: [
      'fleet portal',
      'manager portal',
      'control centre',
      'dashboard',
      'operator tools',
      'fleet management',
      'transport manager',
      'office dashboard',
      'web portal',
      'management portal',
    ],
    answer:
      'The fleet portal gives managers a clearer view of drivers, vehicles and daily compliance workflows. It is being built to support driver records, vehicle checks, defects, incidents, expenses, reports, tachograph analysis, document reminders, maintenance visibility, messages and Atlas assistant summaries.',
    followUps: ['Vehicle checks', 'Defects', 'Reports', 'Tachograph', 'Atlas assistant'],
  },

  {
    id: 'tachograph',
    title: 'Tachograph analysis',
    keywords: [
      'tachograph',
      'tacho',
      'driver card',
      'read card',
      'card reader',
      'ddd file',
      'c1b file',
      'v1b file',
      'vu file',
      'vehicle unit',
      'infringements',
      'tacho analysis',
      'tachograph analysis',
      'tachograph files',
    ],
    answer:
      'The portal is being built to support driver card and vehicle unit file import and analysis. The aim is to show clear activity timelines, totals, events, infringements and exportable reports. HourWise supports compliance review but does not replace legal tachograph equipment, official records or operator responsibility.',
    followUps: ['Driver card', 'Vehicle unit', 'Infringements', 'Compliance disclaimer'],
  },

  {
    id: 'driver-card',
    title: 'Driver card support',
    keywords: [
      'driver card',
      'card download',
      'driver card download',
      'read driver card',
      'card reader',
      'smart card',
      'driver card view',
      'card analysis',
      'c1b',
      'ddd',
    ],
    answer:
      'HourWise is being built to support driver card import and review. The goal is to show driver details, card information, activity timelines, daily totals, weekly totals, events, possible infringements and exportable reports in a clear visual format. This is intended to make review easier for managers and drivers.',
    followUps: ['Tachograph analysis', 'Vehicle unit', 'Reports', 'Compliance disclaimer'],
  },

  {
    id: 'vehicle-unit',
    title: 'Vehicle unit file support',
    keywords: [
      'vehicle unit',
      'vu',
      'vu file',
      'vehicle unit file',
      'v1b',
      'download vehicle unit',
      'vehicle download',
      'tachograph head unit',
      'truck unit',
    ],
    answer:
      'Vehicle unit file support is planned so operators can import and review vehicle tachograph data alongside driver records. The aim is to help with activity review, vehicle timelines, events, faults, possible infringements and audit-friendly reporting where compatible files are available.',
    followUps: ['Tachograph analysis', 'Driver card', 'Fleet portal'],
  },

  {
    id: 'infringements',
    title: 'Will HourWise show infringements?',
    keywords: [
      'infringements',
      'violations',
      'offences',
      'breaches',
      'rules broken',
      'tacho infringements',
      'driving hours infringement',
      'working time infringement',
      'compliance warning',
    ],
    answer:
      'The portal is being built to highlight possible issues, warnings and infringements in a clearer format. These should be treated as compliance support and review aids, not legal decisions. Operators remain responsible for checking records, keeping evidence and meeting their legal obligations.',
    followUps: ['Tachograph analysis', 'Compliance disclaimer', 'Reports'],
  },

  {
    id: 'vehicle-checks',
    title: 'Vehicle checks and defects',
    keywords: [
      'vehicle checks',
      'daily checks',
      'walkaround checks',
      'defect reporting',
      'defects',
      'vehicle defect',
      'driver checks',
      'pre use checks',
      'pre-use checks',
      'truck checks',
      'fleet checks',
    ],
    answer:
      'HourWise is being built to support daily vehicle checks and defect reporting. Drivers should be able to submit checks from the app, while managers can review missing checks, open defects, resolved defects and vehicle history from the portal.',
    followUps: ['Fleet portal', 'Fleet driver', 'Reports', 'Maintenance'],
  },

  {
    id: 'expenses',
    title: 'Expenses, fuel and receipts',
    keywords: [
      'expenses',
      'receipts',
      'fuel',
      'tolls',
      'mileage',
      'claim expenses',
      'expense reporting',
      'fuel receipts',
      'driver expenses',
      'subsistence',
      'allowances',
    ],
    answer:
      'The app and portal are planned to support driver expenses such as fuel, tolls, mileage, receipts and other work-related costs. Drivers can record information during the day, and managers can review it through the portal for admin, payroll or reporting workflows.',
    followUps: ['Driver app', 'Fleet portal', 'Pay estimates', 'Reports'],
  },

  {
    id: 'pay-estimates',
    title: 'Pay estimates and payroll support',
    keywords: [
      'pay',
      'pay estimates',
      'payroll',
      'wages',
      'driver pay',
      'hourly rate',
      'allowances',
      'overtime',
      'invoice',
      'invoices',
      'billing',
    ],
    answer:
      'HourWise is planned to help drivers and operators understand time, expenses and pay-related records more clearly. The driver app can support pay estimates and allowances, while the portal can support payroll summaries, working time reports and admin review. This is intended to support payroll workflows, not replace final payroll checks.',
    followUps: ['Expenses', 'Reports', 'Solo driver', 'Fleet portal'],
  },

  {
    id: 'reports',
    title: 'Reports and downloads',
    keywords: [
      'reports',
      'download reports',
      'export',
      'pdf',
      'csv',
      'daily report',
      'weekly report',
      'monthly report',
      'records',
      'evidence',
      'audit',
      'print',
    ],
    answer:
      'HourWise is being designed to make records easier to review and export. Planned reports include daily driver summaries, working time records, expenses, vehicle checks, defects, incident records, tachograph summaries and management reports. Export options may vary during beta.',
    followUps: ['Driver app', 'Fleet portal', 'Tachograph analysis', 'Compliance disclaimer'],
  },

  {
    id: 'incidents',
    title: 'Incident and accident reporting',
    keywords: [
      'incident',
      'incidents',
      'accident',
      'accident reporting',
      'damage',
      'near miss',
      'near-miss',
      'report incident',
      'insurance',
      'photos',
    ],
    answer:
      'HourWise is planned to support incident and accident reporting so drivers can capture key details during the day and managers can keep a clearer record in the portal. This may include notes, timestamps, vehicle details, photos and follow-up actions depending on the final implementation.',
    followUps: ['Fleet portal', 'Reports', 'Vehicle checks', 'Defects'],
  },

  {
    id: 'maintenance',
    title: 'Maintenance and PMI reminders',
    keywords: [
      'maintenance',
      'pmi',
      'inspection',
      'service',
      'mot',
      'calibration',
      'vehicle reminders',
      'maintenance reminders',
      'preventative maintenance',
      'vehicle documents',
    ],
    answer:
      'The fleet portal is planned to help operators track vehicle-related reminders such as PMI dates, inspections, maintenance tasks, calibration dates, MOTs and document expiries. The aim is to give managers a clearer view of what needs attention before it becomes a problem.',
    followUps: ['Fleet portal', 'Vehicle checks', 'Reports', 'Atlas assistant'],
  },

  {
    id: 'messaging',
    title: 'Driver messaging',
    keywords: [
      'messaging',
      'messages',
      'chat',
      'driver messages',
      'announcements',
      'office messages',
      'manager messages',
      'send message',
      'contact drivers',
      'communication',
    ],
    answer:
      'HourWise is planned to support messaging between the transport office and fleet-connected drivers. This could include direct messages, announcements, reminders and acknowledgements so important information is not lost across multiple channels.',
    followUps: ['Fleet driver', 'Fleet portal', 'Atlas assistant'],
  },

  {
    id: 'atlas-assistant',
    title: 'What is Atlas?',
    keywords: [
      'atlas',
      'atlas assistant',
      'ai assistant',
      'chatbot',
      'assistant',
      'fleet assistant',
      'ask atlas',
      'ai',
      'what is atlas',
    ],
    answer:
      'Atlas is the planned HourWise assistant. On the coming-soon homepage, Atlas is a simple preview chatbot with prepared answers about HourWise. In the full portal, Atlas is planned to help managers ask questions about fleet records, missing checks, upcoming expiries, tachograph issues, driver risk areas and daily summaries.',
    followUps: ['Fleet portal', 'Features included', 'Early access', 'Suggest a feature'],
  },

  {
    id: 'feature-request',
    title: 'Can I suggest a feature?',
    keywords: [
      'suggest a feature',
      'feature request',
      'request a feature',
      'can you add',
      'could you add',
      'i need a feature',
      'i want a feature',
      'feedback',
      'idea',
      'suggestion',
      'beta feedback',
    ],
    answer:
      'Yes. Feature feedback is very welcome, especially during early access. If there is a workflow you currently manage with spreadsheets, WhatsApp, paper forms or separate systems, we would like to hear about it so HourWise can be shaped around real transport problems.',
    followUps: ['Early access', 'Contact HourWise', 'Features included'],
    cta: { label: 'Send feedback through early access', action: 'earlyAccess' },
  },

  {
    id: 'pricing',
    title: 'Pricing expectations',
    keywords: [
      'pricing',
      'price',
      'cost',
      'how much',
      'subscription',
      'monthly fee',
      'plans',
      'charges',
      'paid',
      'free trial',
      'beta price',
    ],
    answer:
      'Initial pricing is expected to be simple: the solo driver app planned around £2.99/month, the fleet portal from around £19.99/month, and fleet-connected drivers around £2.99 per driver/month. Prices may change during beta as features are finalised.',
    followUps: ['Solo driver', 'Fleet pricing', 'Early access'],
  },

  {
    id: 'fleet-pricing',
    title: 'Fleet pricing',
    keywords: [
      'fleet pricing',
      'operator pricing',
      'company pricing',
      'cost for fleets',
      'fleet cost',
      'price for operators',
      'how much for fleet',
      'per driver',
      'per vehicle',
    ],
    answer:
      'Fleet pricing is expected to start from around £19.99/month for the portal, with fleet-connected driver app access planned around £2.99 per driver/month. The final pricing may depend on fleet size, modules, beta feedback and which features are enabled.',
    followUps: ['Pricing', 'Fleet portal', 'Early access'],
    cta: { label: 'Register interest', action: 'earlyAccess' },
  },

  {
    id: 'early-access',
    title: 'How to get access',
    keywords: [
      'early access',
      'join',
      'sign up',
      'signup',
      'beta',
      'test',
      'register',
      'waiting list',
      'waitlist',
      'launch',
      'when can i use it',
      'available',
      'release date',
    ],
    answer:
      'You can request early access from the homepage. We are especially interested in feedback from solo drivers, small fleets, transport managers and compliance professionals during the beta phase. Early access helps shape which features are prioritised first.',
    followUps: ['Beta testing', 'Request access', 'Features included'],
    cta: { label: 'Go to early access form', action: 'earlyAccess' },
  },

  {
    id: 'current-status',
    title: 'Is HourWise available now?',
    keywords: [
      'is it available',
      'available now',
      'can i download',
      'is it live',
      'coming soon',
      'when is launch',
      'release',
      'beta status',
      'is it ready',
      'can i use it yet',
    ],
    answer:
      'HourWise is currently in build and preparation for early access. The goal is to launch carefully with useful driver and fleet workflows, gather feedback from real users, and continue improving the app and portal before wider release.',
    followUps: ['Early access', 'Features included', 'Driver app', 'Fleet portal'],
    cta: { label: 'Join the early access list', action: 'earlyAccess' },
  },

  {
    id: 'android-ios',
    title: 'Will there be Android and iPhone apps?',
    keywords: [
      'android',
      'iphone',
      'ios',
      'apple',
      'app store',
      'google play',
      'mobile platforms',
      'phone app',
      'tablet',
    ],
    answer:
      'The driver app is being built with mobile use in mind. Android is expected first, with iPhone/iOS planned as part of the wider roadmap. The fleet portal is web-based so managers can access it from a browser.',
    followUps: ['Driver app', 'Early access', 'Fleet portal'],
  },

  {
    id: 'uk-eu',
    title: 'Is HourWise for the UK or Europe?',
    keywords: [
      'uk',
      'europe',
      'eu',
      'ireland',
      'international',
      'where does it work',
      'countries',
      'uk drivers',
      'european drivers',
      'hgv europe',
    ],
    answer:
      'HourWise is being designed around UK and European commercial driver workflows, including driver hours, working time, tachograph records and fleet compliance needs. The initial focus is UK/EU transport, with future expansion possible once the core platform is stable.',
    followUps: ['Driver app', 'Tachograph analysis', 'Compliance disclaimer'],
  },

  {
    id: 'vans-light-commercial',
    title: 'Will HourWise support vans and light commercial vehicles?',
    keywords: [
      'vans',
      'van drivers',
      'light commercial',
      '3.5t',
      '2.5t',
      'lcv',
      'small vans',
      'van fleet',
      'international vans',
    ],
    answer:
      'HourWise is primarily being built around professional driver and fleet workflows, starting with HGV-style compliance needs. The platform is also being designed with flexibility in mind so future vehicle profiles, including vans or light commercial vehicles, can be considered where they fit the compliance and fleet management use case.',
    followUps: ['Fleet portal', 'Vehicle checks', 'Tachograph analysis', 'Early access'],
  },

  {
    id: 'gps-tracking',
    title: 'Does HourWise track driver location?',
    keywords: [
      'gps',
      'tracking',
      'location',
      'track drivers',
      'live tracking',
      'driver location',
      'vehicle location',
      'privacy',
      'company phone',
    ],
    answer:
      'The driver app uses movement and location-related signals to support driving and shift detection where permissions allow. Full fleet location tracking is a separate privacy-sensitive feature and would need clear controls, consent, company policy and suitable use cases. HourWise is not intended to secretly track drivers.',
    followUps: ['Driver app', 'Privacy', 'Fleet portal'],
  },

  {
    id: 'privacy-security',
    title: 'Privacy and security',
    keywords: [
      'privacy',
      'security',
      'gdpr',
      'data protection',
      'data',
      'secure',
      'who can see my data',
      'driver privacy',
      'personal data',
    ],
    answer:
      'HourWise is being built with privacy and security in mind. Fleet-connected data should only be visible to authorised users within the correct company account. Drivers and operators should have clear expectations about what information is captured, why it is needed and who can access it.',
    followUps: ['Fleet driver', 'GPS tracking', 'Compliance disclaimer', 'Contact HourWise'],
  },

  {
    id: 'compliance-disclaimer',
    title: 'Is HourWise a tachograph replacement?',
    keywords: [
      'legal advice',
      'dvsa approved',
      'certified',
      'law',
      'compliance ruling',
      'tachograph replacement',
      'replace tachograph',
      'official records',
      'operator responsibility',
      'legal',
      'is this legal',
    ],
    answer:
      'No. HourWise is a support, tracking and reporting tool. It does not provide legal advice, replace tachograph equipment, replace official records or remove operator responsibility. It is designed to help make records, warnings and review workflows clearer.',
    followUps: ['Tachograph analysis', 'Infringements', 'Contact HourWise'],
  },

  {
    id: 'small-fleets',
    title: 'Is HourWise suitable for small fleets?',
    keywords: [
      'small fleet',
      'small fleets',
      'few vehicles',
      'one truck',
      'two trucks',
      'small operator',
      'family business',
      'startup fleet',
      'affordable fleet software',
    ],
    answer:
      'Yes. HourWise is especially aimed at solo drivers, small fleets and growing operators who need practical compliance and fleet admin tools without the complexity or cost of large enterprise systems. The goal is to make important records easier to capture, review and act on.',
    followUps: ['Fleet portal', 'Pricing', 'Vehicle checks', 'Early access'],
  },

  {
    id: 'competitors',
    title: 'How is HourWise different?',
    keywords: [
      'competitors',
      'alternative',
      'why hourwise',
      'how is it different',
      'unique',
      'advantages',
      'better than',
      'why use this',
      'why should i care',
    ],
    answer:
      'HourWise aims to combine several workflows that are often split across separate tools: driver hours, app-based records, vehicle checks, expenses, incidents, tachograph analysis, reports, reminders and fleet communication. The focus is practical day-to-day use for real drivers and smaller operators, not just large enterprise fleets.',
    followUps: ['Features included', 'Driver app', 'Fleet portal', 'Atlas assistant'],
  },

  {
    id: 'contact',
    title: 'Contact HourWise',
    keywords: [
      'contact',
      'email',
      'support',
      'help',
      'talk to founder',
      'team',
      'speak to someone',
      'get in touch',
      'message',
      'inquiry',
      'enquiry',
    ],
    answer:
      'You can contact the team at info@hourwiseeu.co.uk for general enquiries or support@hourwiseeu.co.uk for technical help. For Atlas-specific feedback, you can reach out to Atlas@hourwiseeu.co.uk.',
    followUps: ['Early access', 'Suggest a feature'],
  },

  {
    id: 'unknown-help',
    title: 'What can I ask Atlas?',
    keywords: [
      'help',
      'what can i ask',
      'questions',
      'commands',
      'options',
      'menu',
      'topics',
      'ask atlas',
      'examples',
    ],
    answer:
      'You can ask Atlas about HourWise, the driver app, the fleet portal, tachograph analysis, vehicle checks, expenses, pricing, early access, privacy, Atlas assistant plans, or how to suggest a feature. Try asking: “What features will be included?”, “Is this for solo drivers?”, “How does the fleet portal work?” or “Can I suggest a feature?”',
    followUps: ['Features included', 'Driver app', 'Fleet portal', 'Early access'],
  },
];